services:
  # Development service
  lotlogic-react-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:5173"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0