# services:
#   # Development service
#   lotlogic-react-dev:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     ports:
#       - "3002:5173"
#     environment:
#       - NODE_ENV=development
#     env_file:
#       - .env
#     volumes:
#       - .:/app
#       - /app/node_modules
#     command: npm run dev -- --host 0.0.0.0



services:
  lotlogic-react-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev   # use the dev Dockerfile below
    ports:
      - "3002:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true   # helps file watching in containers
    env_file:
      - .env
    volumes:
      - .:/app                      
      - node_modules:/app/node_modules   # keep deps in a named volume
    command: >
      sh -c "npm ci || npm i; npm run dev -- --host 0.0.0.0"

volumes:
  node_modules: {}
